#!/bin/bash

filenote=$HOME/.notes_conky.txt

fileconky=$HOME/.config/conky/shortcuts.conkyrc

vim $filenote

while [[ $(tail -n 1 $fileconky) != '${hr}' ]]
do
	sed -i '$d' $fileconky
done

cat $filenote >> $fileconky
echo -e "\n]];" >> $fileconky
